### ISSUE TITLE
[Frontend] Create Youtube Iframe Component

### ISSUE THREAD

**Issue by jirheee** [CS492-FE-Dev-Team-Project/FE-Dev-Client#1]
## Description
유튜브 iframe api문서가 vanilla js로 되어 있어서 react component로 만들어야함

**Comment by jirheee** [comment]
아 그리고 지금 eslint rule이 no-explicit-any에 warning 띄워져서 노란줄 뜰텐데, 그걸 그냥 off시키도록 설정시킬 수도 있어요!
어떻게 하는게 좋을까용?

**Comment by hy2850** [comment]
👍🏻 그럼 대안들 + 제시한 모듈 2가지의 타입 참고해서 타입을 짜보도록 하겠습니다.
ESLint rule은 그냥 두는게 나을 것 같아요. 사실 any를 써서 Type check를 막으면 TS 사용하는 의미가 없기도 하니까요.

**Comment by jirheee** [comment]
React-Youtube 라이브러리로 우리가 필요한 기능들 다 사용할 수 있을 것 같아서 React-Youtube 쓰기로 결정함.
