### ISSUE TITLE
[Frontend] ClassCard Bug

### ISSUE THREAD

**Issue by jirheee** [CS492-FE-Dev-Team-Project/FE-Dev-Client#100]
아래처럼 ClassCard가 늘어져 보이는 버그가 있습니다.
![image](https://user-images.githubusercontent.com/65358599/144228986-8be5488f-0a25-4c87-b51a-f215201638d5.png)

**Comment by Jung-Sanghyun** [comment]
클래스 카드가 1개일 때를 고려하지 못했습니다. 수정하겠습니다.

**Comment by hy2850** [comment]
여러 ClassCard가 서로 붙지 못하고, 빨간색으로 표시한 부분이 버튼으로서 자리를 차지하고 있는데, 저만 겪는 버그인지 궁금합니다.

![image](https://user-images.githubusercontent.com/39735858/144365716-d7608e7d-c64b-4735-baac-816e29e48df7.png)

**Comment by Jung-Sanghyun** [comment]
classcard가 많은 상태로 테스트하다보니 미처 신경쓰지 못했습니다. 버그들 금방 수정하겠습니다.
