### ISSUE TITLE
[Frontend+Backend] ClassroomPage: Youtube Component

### ISSUE THREAD

**Issue by jirheee** [CS492-FE-Dev-Team-Project/FE-Dev-Client#12]
- [x] react-youtube 이용해서 메인 컨텐츠 같이 볼 수 있도록
  - [x] Sync with instructor

**Comment by hy2850** [comment]
[Loading a video player](https://developers.google.com/youtube/iframe_api_reference#Loading_a_Video_Player) 단계에서 'playerVars'라는 옵션을 사용해서 video player의 특성을 설정해줄 수 있는데, `controls`나 `disablekb`를 통해 유저가 비디오 컨트롤을 못하게 막을 수 있네요 ([링크](https://developers.google.com/youtube/player_parameters#:~:text=the%20modestbranding%20option.-,controls,-This%20parameter%20indicates)). 

이걸 쓰면 학생들이 비디오를 못 건들이게 하는 문제를 해결할 수 있을 것 같습니다.

**Comment by jirheee** [comment]
오 대박 그러면 괜히 복잡하게 할 필요가 없었네요 😃
그리고 서버랑 웹소켓으로 소통하는거 필요하시면 #17 웹소켓 예시 코드 참고하시면 될 것 같아요!

**Comment by hy2850** [comment]
#### Instructor
현재 선생님 시간 - player.getCurrentTime
https://developers.google.com/youtube/iframe_api_reference#getCurrentTime

선생님 시간을 매초 학생들에게 뿌려주기?
* setInterval 사용
* ... 다른 방법?

[링크1](https://stackoverflow.com/questions/48893722/react-youtube-get-live-playtime-and-set-playtime)
[링크2](https://stackoverflow.com/questions/22650281/how-to-detect-change-in-youtube-getcurrenttime)


#### 학생들
시간 설정 - player.seekTo
https://developers.google.com/youtube/iframe_api_reference#seekTo

**Comment by jirheee** [comment]
선생님의 시간을 매초 뿌려주는 방법은 오버헤드가 좀 클 것 같고, 기본적으로는 선생님의 action만 학생들에게 전달하되, 특정 시간마다 학생들과 선생님의 재생 시간 차이를 계산하고, 싱크가 차이가 크다면 그때 선생님의 시간과 싱크를 맞추는 방법은 어떨까요?

**Comment by hy2850** [comment]
좋은 생각 같습니다! 

> 특정 시간마다 학생들과 선생님의 재생 시간 차이를 계산하고
이 부분은 
1. setInterval로 각 클라이언트가 따로 해야할 지, 
2. 아니면 서버에서 마찬가지로  setInterval로 주기적으로 신호를 보내줄 지 
두 가지 방법이 떠오르는데 어떠신가요?

**Comment by jirheee** [comment]
음 사실 지금 바로 어떤 방법을 결정하기가 어려운게, 어떤 시나리오가 가능한지 실험을 해봐야 할 것 같아요. 현재 저희가 생각하는 싱크 문제가 광고 영향이 제일 클 것이라고 생각하고 있는데, (1) 광고가 어떤 빈도로 랜덤하게 삽입되는지도 정확히 모르고 (2) 만약에 특정 학생만 광고에 걸렸을 경우에 youtube player에서 변수가 어떻게 세팅되는지를 모르기 때문에 결정하기가 어려운 것 같습니다.

**Comment by jirheee** [comment]
그리고 지금 든 생각은 주기적으로 그런걸 할 필요가 아예 없을 것 같다는 생각이 드는게, 학생이 광고에 들어갔다가 나오게 되면 원래 재생하던 시간부터가 아닌 선생님의 재생 시간에 맞추는 방법도 있을 것 같네요. 어차피 싱크 안맞았을 경우에 강제로 점프시킬거라면 그냥 처음부터 항상 선생님의 시간에 싱크를 맞추는게 베스트 아닐까요?

**Comment by hy2850** [comment]
일단은 선생님이 비디오 시간을 바꾸면, socket.io로 그 정보를 학생들에게 뿌려서 동일한 시간대를 보도록 기능을 구현해보겠습니다.

> (2) 만약에 특정 학생만 광고에 걸렸을 경우에 youtube player에서 변수가 어떻게 세팅되는지를 모르기 때문에...
→ onStateChange에 PAUSED or (2)로 뜬답니다. ([stackoverflow](https://stackoverflow.com/questions/39541430/youtube-iframe-api-video-ad-events))

또 #21 '새로 배운 부분 - 광고 처리'에, 광고 처리에 관해 트위치 사진을 하나 첨부했는데 참고해주시면 좋을 것 같아요.

**Comment by jirheee** [comment]
음 형님이 올려주신 사진 보고왔는데, 학생이 광고가 나오면 선생님의 화면을 작게 띄우자는 의견인건가요?

**Comment by hy2850** [comment]
저렇게 하는게 깔끔하긴 한데, 일단은 광고 나올 시 학생 화면을 가리는 것을 먼저 구현해보겠습니다.

**Comment by jirheee** [comment]
좋은 아이디어인 것 같습니다! 수요일 회의때 이야기해보면 좋을 것 같아요!

**Comment by hy2850** [comment]
외부에서 소켓을 만들어서, 특정 room에 집어넣은 뒤,
소켓은 제작한 YouTube 컴포넌트에 props로 넣어주는 방식으로 구현하려고 하는데,
connected 되기 전에 렌더링이 완료해버려서 null값이 전달되네요 ㅠㅠ

YouTube 컴포넌트에 key props 설정한 뒤, `useEffect[connected]` 맨 마지막에 `setKey(key=>key+1);`로 해서 강제 re-rendering 유도해보는 방법이 생각났는데 어떠신가요

**Comment by jirheee** [comment]
음 코드를 보여주실 수 있으신가요?

**Comment by hy2850** [comment]
fdbc413e457e7873c991db859cd4bb9700f22126
`client/src/components/youtube.tsx`가 YouTube 컴포넌트고,
`client/src/pages/youtubeTestPage_instructor.tsx`가 testPage입니다.

**Comment by jirheee** [comment]
아 제가 이해한게 맞는 것 같네요 여쭙고 싶은게 소켓을 Prop으로 넣으시려고하는 특별한 이유가 있나요?

**Comment by jirheee** [comment]
그리고 다음부터는 코드블럭으로 복붙하시면 더 좋을 것 같네요...! 들어가니까 수정한 코드가 많아서 가독성이 안좋을 것 같습니다!

**Comment by hy2850** [comment]
제가 생각한 디자인은, 
1. YouTube 컴포넌트를 사용하는 페이지 쪽에서 먼저 socket 셋팅을 해서 원하는 room에 들어간 뒤,
2. YouTube 컴포넌트는 어떤 room인지는 신경 쓸 필요 없이 비디오 관련 작업만 처리한다
였습니다.
(다시 생각해보니까, 그냥 room 넘버만 넘겨주는 식으로 처리하는게 편하겠네요)

중요한 점은, react-youtube라이브러리를 사용할 땐, video player 객체를 참조할 수 있는 방법이 onReady, onStateChange같은 이벤트 핸들러로 전달받는 evt.target 값으로만 참조할 수 있습니다.
그래서 비디오 관련 작업은 무조건 YouTube 컴포넌트 내부에서 처리해야해요

**Comment by jirheee** [comment]
제 생각엔 `useSocket.tsx`와 `socketProvider.tsx`를 한번 읽어보시면 좋을 것 같은데, 소켓은 전역으로 하나만 존재하고 socketProvider내부에서 관리합니다. 그리고 useSocket을 쓰면 해당 소켓을 돌려줍니다. 따라서 useSocket을 Youtube component안에서 사용하면 문제가 없을 것 같네요.

**Comment by jirheee** [comment]
제가 머지했던 TestSocketPage를 참고하면 좋을 것 같습니당!

**Comment by jirheee** [comment]
그리고 지금 보니까 enum no shadow error때문에 const로 하신것같은데, 이거 eslint error라고 하더라구요! `eslintrc` 수정해서 메인에 머지해둘게요!

**Comment by hy2850** [comment]
nodemon flag -L 추가
c660ac968f7721cec6875b44cf4c5b7ccb8842ab
eslint prettier rule 바꿔서 CRLF 문제 해결
50dd1ca404ff51ef090267fb0b9cc4b9accfcef3

브랜치 커밋인데, 메인에 할껄 그랬네요. 저 내용들 메인에 바로 푸쉬할까요?

**Comment by jirheee** [comment]
아 네네 그러면 될 것 같아요

**Comment by hy2850** [comment]
지금 cover 구현을 위한 구조가 아래와 같습니다. 
맨 바깥에 wrapper (`id="youtube-wrapper"`)가 감싸고있고, video-cover div와 video-container div가 나란히 놓여져 있습니다.
```JS
// youtube.tsx
return (
  <div
    className={studentNumber === -1 ? 'teacher' : 'student'}
    id="youtube-wrapper"
    ref={videoWrapper}
  >
    <div className="video-cover" style={coverStyles} />
    <div className="video-container">
      <YouTube
        videoId="j1_5ttGRzFs"
        opts={options}
        onReady={onReady}
        onStateChange={onStateChange}
      />
    </div>
  </div>
);
```

cover를 씌워야 하는 경우엔, 겉 wrapper의 classList에 'coverVideo' class를 추가합니다.
```JS
// youtube.tsx
videoWrapper.current?.classList.add('coverVideo');
```

CSS에서 cover를 이렇게 정의했는데, 현재 cover 사이즈 조절이 안되는 상황입니다 (아래는 500px로 하드코딩된 상황)
```CSS
/* cover shows up */
#youtube-wrapper.coverVideo .video-cover {
  visibility: visible;
  background-color: black;
  opacity: 1;
  height: 500px; /* 이 사이즈를 어떻게 조절하지? */
  -webkit-transition: all 0.5s;
  transition: all 0.5s;
}
```

`height: 100%;`도 안되네요.
