### ISSUE TITLE
[Frontend] ClassroomPage: Timeline Component

### ISSUE THREAD

**Issue by jirheee** [CS492-FE-Dev-Team-Project/FE-Dev-Client#13]
** Youtube 컴포넌트 만든 뒤에 하면 될 것 같습니다
- [x] Youtube Timeline 위에 마커 넣기
- [x] 마커 클릭 시 해당 마커에 관한 것으로 채팅창 덮어씌우기 → #45

**Comment by hy2850** [comment]
목표

- [ ] Overlay 마커 만들기

- [ ] 특정 시간 위에 마커 놓을 수 있도록

**Comment by hy2850** [comment]
문제 한줄 요약 : 외부에서 생성된 Timeline flag info를 YouTube 컴포넌트 안에 전달해주는 방법?
대안 한줄 요약 : flagInfo를 전역으로 상태관리를 하면 굉장히 편할텐데.. context + useReducer 활용?

처음에는 #12 YouTube 컴포넌트 안에서 Timeline flag 정보를 관리하려고 했습니다 (아래 코드)
그런데, 외부에서 버튼을 클릭해서 Timeline flag를 생성할텐데, 이 정보를 YouTube component 까지 끌어서 넣어줘야 하는게 어려울 것 같다는 생각이 들었습니다.

```JS
// client/src/component/youtube.tsx
interface flagInfo {
  time: number;
  message: string;
}

const YouTubePlayer = (...) => {
  const [flagInfoArr, setFlagInfoArr] = useState<Array<flagInfo>>([]);
  ...
  return(
    <>
      {flagInfoArr.map((info, idx) => (
        <Flag time={info.time} />
      ))}
      ...
    </>
  )
}
```

**Comment by jirheee** [comment]
음 flag는 어차피 네트워크에서 받아와야하는 값이니 여기서 api호출하면 될 것 같아요!

**Comment by hy2850** [comment]
현재 iframe 전체의 커서 이벤트를 CSS로 막은 상태인데,
Iframe 위를 마우스로 Hover할 시 progress bar같은 control UI는 뜨게 하되, Click만 막는 방법을 찾아보고 있는데 잘 안되네요.

```JS
// youtube.tsx
return (
  <div
    className={studentNumber === -1 ? 'teacher' : 'student'}
    id="youtube-wrapper"
    ref={videoWrapper}
    style={{
      width,
      height
    }}
  >
    {flagInfoArr.map((info, idx) => {
      const MAX = videoDuration.current;
      return <Flag time={(info.time / MAX) * 100} message={info.message} />;
    })}

    <div className="video-cover" style={coverStyles} />
    <div className="video-container">
      <YouTube
        videoId={videoId}
        opts={options}
        onReady={onReady}
        onStateChange={onStateChange}
      />
    </div>
  </div>
);
```

```CSS
.student#youtube-wrapper .video-container {
  pointer-events: none;
}
```

**Comment by hy2850** [comment]
iframe 혹은 iframe을 감싸는 wrapper div에 제가 원하는 click event listener를 설정하는 것으로는 click을 막기가 힘들다는 결론에 도달했습니다. ([참고1](https://stackoverflow.com/questions/11893171/how-to-capture-onclick-within-an-iframe-for-embedded-youtube-video) [참고2](https://stackoverflow.com/questions/7260605/how-can-i-track-a-click-event-of-an-embedded-video-youtube-vimeo-etc-to-t))

2가지 대안을 제시합니다 (participant 화면 기준입니다)

1. player의 기본 UI (재생 버튼, progress bar 등)를 유지하고 클릭을 허용하되, playerState가 PLAYING으로 바뀔 때 (ex. paused -> playing) instructor의 현재 시간에 맞추기
![image](https://user-images.githubusercontent.com/39735858/141712925-3ec338f5-5b0b-487c-9e84-271d313fea9a.png)

장점 : Progress bar가 보여서 timeline component UI 디자인이 깔끔함
단점 : 클릭 가능. Participant가 마음대로 영상을 멈추거나 소리를 조절할 수 있음.

2. player의 기본 UI 제거, YouTube화면 클릭도 disable
![image](https://user-images.githubusercontent.com/39735858/141713517-1bf2948b-78cc-4406-8330-ae6cf051eeb7.png)

장점 : 클릭 불가능. Participant가 딴 짓 못하고, 무조건 instructor 화면 따라감
단점 : Progress bar가 안보여서, timeline component가 붕 뜨게됨.
