### ISSUE TITLE
[Backend/Bug] when new user joins a class

### ISSUE THREAD

**Issue by hy2850** [CS492-FE-Dev-Team-Project/FE-Dev-Client#130]
## 개요
새 유저가 class에 join할때 아래와 같이 에러가 나면서 서버가 작동을 중지합니다.

![image](https://user-images.githubusercontent.com/39735858/144798580-0d80fb56-2eb2-4259-b9a5-edd2179034bb.png)

## 원인

class 인스턴스의 member 배열에 해당 유저가 없는데도 `getMemberById`로 찾아오려고 해서.
어찌되면 에러가 나는게 당연한게, 새 유저를 class에 추가하는데 기존 class.member 배열에서 그 유저를 찾으려 하는거니까

```ts
// OnJoinClass
cls.getMemberById(user!.id).setConnectStatus(true); // error
```

## 대안
`JoinClass` 이벤트 시, class.member에 유저를 추가

**Comment by jirheee** [comment]
작동하도록 고쳐서 푸시했습니다! 마저 하시면 될 것 같습니다 :)
