### ISSUE TITLE
[Bug] react-youtube not playing/pausing after re-rendering

### ISSUE THREAD

**Issue by hy2850** [CS492-FE-Dev-Team-Project/FE-Dev-Client#133]
`lecturePage-revamp#113` 브랜치의 793772ddb73a3644cba1d7739b4db916869fae4f 커밋

## 개요
1. Lecture page에서, Instructor가 Live 상태를 바꾼다.
(youtube.tsx Line46의 `const [isLive, setIsLive] = useState(true);` 가 원래 false여야함. 테스트를 위해 true로 바꿨는데 미처 안바꿔놨네)

![image](https://user-images.githubusercontent.com/39735858/144825498-0b7302be-e1cc-49e7-842c-bbb811e3c1ac.png)

2. 그러면, participant의 youtube iframe의 옵션이 바뀌며 (컨트롤 가능/불가능) re-rendering됨
3. 이후 instructor가 영상 play, pause 등을 하면, 소켓으로 participant에게 명령이 전달은 되지만, `video?.pauseVideo();`, `video?.playVideo();` 등 명령에서 아래와 같이 에러가 남.

![image](https://user-images.githubusercontent.com/39735858/144825345-d8dd51c5-dba5-4164-be94-bae3b20098c5.png)

골때리는점은, onReady, onPlay등 함수에서 호출하는 함수는 잘 되는데, 왜 소켓 관련된 play, pause 함수만 안되는건지 모르겠음

```js
// Initialize
const onReady = (evt: any) => {
  // evt.target.playVideo(); // ⚡️ 여기도 잘됨

  setVideo(evt.target);
  videoDuration.current = evt.target.playerInfo.duration;
};

const onPlay = (evt: any) => {
  intervalID.current = setInterval(() => {
    // video.pauseVideo(); // ⚡️ 여기서 호출하면 잘됨
    setVideoCurrent(video.getCurrentTime());
  }, 100);
};
```

Socket listener쪽 play, pause 함수들 (안됨, 에러남)

```
useEffect(() => {
  // If not instructor, sync video time, play, and pause
  if (connected && !!video) {
    if (memberType === MemberType.STUDENT) {
      console.log('didvideo change? ', video);

      socket?.on('InstructorTimeChange', (newtime: number) => {
        video?.seekTo(newtime); // 🔥
      });
      socket?.on('InstructorPlay', () => {
        video?.playVideo(); // 🔥
      });
      socket?.on('InstructorPause', () => {
        console.log(video);
        console.log(video.pauseVideo);

        video?.pauseVideo(); // 🔥
      });
    }
```

### Reproduce 방법

1. instructor랑 participant 이렇게 창 2개 켜두고
2. instructor쪽에서 live 상태 바꿔준다음에 participant가 리렌더링된거 확인하고
3. instructor쪽에서 영상 컨트롤을 해보기
 
그럼 원래 소켓 통해서 instructor가 participant의 영상을 제어할 수 있어야 하는데 안됨

**Comment by jirheee** [comment]
- 6614c403e56fa887417f4b42dc979c5d05f2c2d2 이 커밋에서 부분적으로 이슈 해결했습니다! :)

**Comment by hy2850** [comment]
* 7f0da21ebd345b2466f1b338db7b9faae4e12dd8
에서 완전히 해결했습니다.
(socket event clean-up, 매 초마다 영상 현재 progress 확인하던 setInterval 초기화)
