### ISSUE TITLE
[Design] 디자인 프레임워크 선택

### ISSUE THREAD

**Issue by jirheee** [CS492-FE-Dev-Team-Project/FE-Dev-Client#16]
## Description
빠르게 빠르게 개발하기 위해 디자인 프레임워크 도입하기로 결정함

## Candidates
1. ant design
2. chakra ui

**Comment by jirheee** [comment]
1. antd (로비 페이지 구현 3시간)
참고: 13fea37813547a18433fdd97cf6c00743005e496
**fact:**
통계적으로 가장 많이 사용하는 UI 프레임워크라고 합니다
다양한 컴포넌트들이 구현되어 있고 다른 UI framework에는 존재하지 않는 date picker, auto-complete같은 컴포넌트가 있습니다.
앤트 디자인을 만든 사람들이 생각하는 좋은 디자인에 대한 철학들을 기반으로 만들어졌습니다.
**opinion**
개인적으로 스타일을 커스터마이징하는데에 조금 오래걸렸던 것 같습니다.
기본적으로 하나의 테마가 주어지고 바꾸려면 스타일 prop으로 CSS Object(ex. `style={width: "100px"}`)를 주는 방식을 사용해서 스타일을 먹여야 하는데, 그게 마음에 안들어서 `styled-component`를 이용해서 시간이 더 걸린걸수도..?
또 `:hover` 같은 pseudo class를 사용하려면 공식 문서에서 권장되는 `less`를 사용하거나 `styled-component`를 사용해야 하는 듯 싶습니다.

제대로 사용하려면 좀 공부가 필요할 것 같다는 생각이 들었습니다.

**Comment by jirheee** [comment]
2. chakra-ui (로비 페이지 구현 1시간)
참고: b337e5b7a22a9e39df1cf6d7de6f375a4375c79b
**fact:**
- 기본적으로 다크 모드를 지원합니다.
- 인라인 스타일을 이용해서 스타일을 넣을 수 있습니다 ant와의 차이점은 ant는 style prop으로 CSS Object를 넣는 반면에 얘는 바로 property를 넣을 수 있습니다.
- 컬러 팔레트에서 색깔을 바로 가져와서 변수처럼 쓸 수 있습니다(ex. `color="gray.50"`)
```js
// ant
const antComponent = () => {
  return <Button style={{width: "100px"}}/>
}
// chakra
const antComponent = () => {
  return <Button w={100}/>
}
```
- pseudo class를 `_hover: [CSS Object]`이런식으로 바로 넣을 수 있습니다
**opinion:**
- 가성비 있게 빠르게 만들 수 있는 것 같습니다. 
- `styled-component`를 사용하거나 하는 등 따로 CSS-in-JS 라이브러리를 사용하지 않아도 괜찮을 것 같습니다. 
- 컬러 팔레트에서 색을 가져와서 아래와 같이 쓸 수 있는데, 이게 상당히 편합니다. (내부적으로 CSS variable을 이용하도록 컴파일되는 것 같습니다)
```
<Box color="gray.100" />
```

**Comment by jirheee** [comment]
@hy2850 @jhlee98 @Jung-Sanghyun 
한번씩 보시고 의견 부탁드립니다! 빨리 정해야 하나로 통일하고 개발 진행할 수 있을 것 같습니다

**Comment by hy2850** [comment]
코드와 각 디자인 라이브러리 API를 보고 왔는데,
antd가 기능이 훨씬 많고 스타일링 자유도를 넓게 주는 반면 (less나 styled-component),
chakra UI는 antd 보다는 기능이 적지만, prop-style 디자인 설정이 가능하고 API가 상대적으로 보기 편하게 되어있어 빠르게 배우고 쓰기 좋을 것 같아요.

그리고 저희 Figma prototype이 Chakra UI package를 써서, 동일한 컴포넌트를 제공하는 chakra UI 라이브러리 사용하는게 더 개발하는데 편리할 것 같습니다.

**Comment by hy2850** [comment]
다시 생각해보니까, prop-style을 매번 넣어주려니까 코드가 너무 난잡해지는 것 같기도 합니다. 
저는 '코드 스타일'은 antd가 좋은데,
아무래도 편의성 면에서는 'chakra-ui'가 나을 것 같아요.

질문) chakra-ui는 CSS 바꾸는 방법이 props-style밖에 없나요?

**Comment by jirheee** [comment]
음 styled-component는 ant에 포함된게 아니라, 외부 라이브러리입니다. ant도 원래는 인라인 스타일을 style={{width:"100px"}} 이런식으로 넣어야하는데, 제가 그게 싫어서 임의로 styled-component를 사용한 것입니다. 차크라도 동일하게 styled component사용하면 됩니다.

**Comment by hy2850** [comment]
차크라도 동일하게 사용할 수 있다면, 저는 차크라를 선택할게요!

**Comment by jirheee** [comment]
그런데 차크라 UI를 사용할거라면, 공식 문서에서 인라인 스타일을 권장하고 있어서 그것을 사용하는게 좋을 것 같긴 합니다. ant도 마찬가지이구요.. 그 이유가 저희가 반응형 UI를 편하게 만들기 위해 UI framework의 기능을 사용하려고 했는데, 그것들은 더차피 인라인 스타일로 넣어야 하는 것 같더라구요

**Comment by jirheee** [comment]
그래서 저는 두가지 중 어차피 인라인을 사용해야한다면 타이핑이 더 잘되어있고, pseudo props도 인라인 스타일로 삽일할 수 있는 chakra가 더 편할 것 같다는 생각입니다.

**Comment by jirheee** [comment]
프레임워크마다 디자인에 대한 철학이 담겨 있는데, 참고해보는것도 좋을 것 같습니다
chakra design principles: https://chakra-ui.com/docs/principles
comparison between chakra and antd: https://chakra-ui.com/docs/comparison
antd design principles: https://ant.design/docs/spec/introduce

**Comment by jhlee98** [comment]
저는 chakra 쪽이 좀 더 좋은 것 같습니다.

**Comment by jirheee** [comment]
그러면 chakra를 이용하는 방향으로 정하도록 하겠습니다! Lobby Page PR도 Chakra로 구현 정리해서 올리도록 하겠습니다.
