### ISSUE TITLE
[개발환경] 윈도우-맥 end-of-line 문자가 달라서 컴파일 실패

### ISSUE THREAD

**Issue by hy2850** [CS492-FE-Dev-Team-Project/FE-Dev-Client#18]
### 발생한 문제
@jirheee 님께서 맥에서 작업하시고 Git에 올린 작업물을 제가 윈도우로 받아서 실행시키려고 했는데, end-of-line(EOL)이 다르다는 prettier 에러가 뜨면서 컴파일이 실패합니다.

![image](https://user-images.githubusercontent.com/39735858/140445259-1595bc4e-3581-447d-ad92-01fd03743a7c.png)

원인은 두 운영체제간에 서로 다른 EOL 문자를 쓰기 때문입니다.
> Microsoft Windows 운영체제에서 작업시, 일반적으로 줄바꿈은 carriage return + line feed (CR+LF) 의 형태를 띄게 된다.
...
Unix 기반의 운영체제에서는 줄바꿈을 line feed (LF) 만을 사용해서 표시한다

https://qvault.io/clean-code/line-breaks-vs-code-lf-vs-crlf/

### 시도해본 방법들
1. VS code 설정 바꾸기 - EOL을 LF로 유지하도록
→ ❌ 각 파일마다 VS code 하단의 CRLF를 LF로 일일히 바꿔줘야 함. Git clone 혹은 새 브랜치 내려받아서 새로운 기능 테스트 할때마다 반복해줘야 함.
https://stackoverflow.com/questions/39525417/visual-studio-code-how-to-show-line-endings

2. Git 설정 바꾸기 - 자동으로 EOL이 바뀌도록
→ ❌git config 바꾸고 git clone해서 다시 코드를 실행해봤는데 여전히 에러가 뜹니다.
https://nochoco-lee.tistory.com/133

3. ESLint, Prettier 설정을 바꿔서 line break 관련 warning/error가 안뜨도록
→ 서로의 개발환경에서 line break가 달라 충돌이 일어나지 않을까요?
https://stackoverflow.com/questions/37826449/expected-linebreaks-to-be-lf-but-found-crlf-linebreak-style

**Comment by jirheee** [comment]
아래 문서 참고하셔서 깃 설정 진행해보시겠어요?
링크: https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings

**Comment by hy2850** [comment]
> 아래 문서 참고하셔서 깃 설정 진행해보시겠어요? 링크: https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings

Global, per-repository setting 모두 해봤는데, 이게 commit 할때만 자동으로 바꿔주는건지 git clone해서 내려받았을 때는 여전히 에러가 뜨네요. 일단은 1번 방법으로 해결했습니다. 

혹시 git 설정 후 3번 방법 적용해서 에러 없애는 방식은 어떻게 생각하시나요

**Comment by jirheee** [comment]
음 그런데 형 혹시 클론한 뒤에 `yarn prettier --write` 실행해 보실 수 있을까요? 프리티어가 아마 자동으로 fix해줄텐데 확인해보고 싶네요
그리고 개발 환경이 다른데 LF와 CRLF가 공존하도록 두는건 좋은 선택이 아닐 것 같아서.. pull하거나 clone했을 때 프리티어가 실행되도록 하는 깃 훅을 설정할 수도 있을 것 같은데, 위에 말씀드린 방법대로 프리티어 실행해서 에러가 해결된다면 이 방법을 이용하는 것도 괜찮을 것 같아요

**Comment by hy2850** [comment]
> 음 그러면 형 혹시 클론한 뒤에 `yarn prettier --write` 실행해 보실 수 있을까요? 

요건 에러 뜨면서 안되네요.
error Command failed with exit code 1.

혹시 yarn 때문인지 싶어서 `npx prettier --write` 해봤는데, 에러는 안뜨지만, EOL이 CRLF에서 안 바뀌는 것 같습니다.
아마 VS code 자체 설정에서 EOL = CRLF로 되어있으면 못 바꾸는 걸수도 있겠네요

**Comment by jirheee** [comment]
ㅜㅜ 그러면 린트 설정을 바꿀까요...?

**Comment by hy2850** [comment]
아니요, 괜찮을 것 같아요!
좀 귀찮긴 하지만, 문제 생기는 파일마다 우측 하단의 'CRLF'를 'LF'로 바꾸면 해결되는 것 같습니다.
![image](https://user-images.githubusercontent.com/39735858/140634201-0aa33b20-4388-4817-8e52-7d5fc0d67536.png)

**Comment by jirheee** [comment]
이 부분은 제가 좀더 찾아보겠습니다 ㅜㅜ 다 일일이 설정하는건 너무 귀찮은 일일 것 같아서... 🤮

**Comment by hy2850** [comment]
`.eslintrc.js`에 다음 라인 추가하는 것으로 해결한 것 같습니다.
일일히 파일마다 우측 하단 CRLF 버튼을 LF로 안 바꿔줘도 될 것 같네요.
```
'prettier/prettier': ['error', { endOfLine: 'auto' }]
```

참고 : https://stackoverflow.com/a/63654585/9720700
