### ISSUE TITLE
PR Template 만들기

### ISSUE THREAD

**Issue by jirheee** [CS492-FE-Dev-Team-Project/FE-Dev-Client#22]
멘토님께서 조언해주신 것처럼 PR을 올릴 때 좀 더 자세하고 명료하게 작성할 수 있도록 템플릿을 만들기로 결정.

일단 멘토링 당시 멘토님께서 보여주신 것을 참고해서 만들어 아래와 같이 만들어 보았습니다. 보시고 수정되었으면 좋겠다 하는 부분 있으시면 코멘트 달아주세요!!

------
## 개요
[이슈와 연결]
1. 문제1
2. 문제2

...

## 상세 설명
1. 문제1
  - 시도한 방법 & 시행착오
  - 리뷰 필요한 부분
  - 질문
2. 문제2
  - 시도한 방법 & 시행착오
  - 리뷰 필요한 부분
  - 질문

...

**Comment by hy2850** [comment]
이대로 진행해도 괜찮을 것 같습니다! 👍
