### ISSUE TITLE
[개발환경] nodemon in docker container not restarting the server

### ISSUE THREAD

**Issue by hy2850** [CS492-FE-Dev-Team-Project/FE-Dev-Client#23]
### 문제점
`server/src` 디렉토리의 코드를 변경해도, `nodemon`이 서버를 재시작하지 않습니다.
`nodemon`은 [chokidar](https://www.npmjs.com/package/chokidar)라는 file-watching library를 사용하는데, 이 기능이 docker에서 제대로 작동하지 않아서 그런 것 같습니다.

<br>

### 에러
`yarn up` 해서 도커 컨테이너 실행 시, nodemon이 실행되긴 하나, 코드가 변경될 시 감지를 못하는지 restart가 이루어지지 않습니다.

![image](https://user-images.githubusercontent.com/39735858/140651100-e3c9d119-d9c3-471a-83e0-982c8c9913a3.png)
<br>

### 해결법
`server/package.json`의 nodemon 실행 부분에 `-L` flag를 추가해주면 됩니다. 
`"start": "nodemon -L"`

[링크1 - stackoverflow](https://stackoverflow.com/questions/57946095/nodemon-doesnt-reload-in-docker-container-when-files-change)
[링크2 - 관련 issue](https://github.com/remy/nodemon/issues/1802)

정상적으로 restart가 되는 모습
![image](https://user-images.githubusercontent.com/39735858/140651290-873ecb36-eec5-47f5-aa48-c9101f8bdd79.png)

**Comment by jirheee** [comment]
이 부분 수정해서 PR올리고 머지하면 어떨까요?

**Comment by hy2850** [comment]
Fix : fef422f8d1f2e79e2f929e0207a04d4fa5bed1aa
