### ISSUE TITLE
[ESLint] static HTML element에 event handler 등록을 위한 rule 수정

### ISSUE THREAD

**Issue by hy2850** [CS492-FE-Dev-Team-Project/FE-Dev-Client#34]
문제점 : div 같은 static element에 event handler를 등록하려고 하면 2가지 ESLint 에러가 뜨면서 컴파일이 안됩니다.

* Visible, non-interactive elements with click handlers must have at least one keyboard listener. eslint(jsx-a11y/click-events-have-key-events)
* Static HTML elements with event handlers require a role. eslint(jsx-a11y/no-static-element-interactions)
		
찾아보니, 버튼 같이 직관적으로 이 HTML element가 어떤 역할인지 알 수 있는게 아니라면, 접근성(accessibility) 향상을 위해 type, role 등을 설정하고 keydown event를 추가로 설정해줘야 한다네요.

해결책 : div를 button으로 바꾸면 됩니다.
하지만, 지금 YouTube 화면 클릭을 막는 기능을 event handler로 구현하려는 것이므로, div를 button으로 바꾸는 것은 적절하지 않다고 생각합니다.
접근성이 있으면 좋지만, 일단 핵심 기능 구현이 먼저라고 생각해서 disable rule을 제안합니다.

```JS
// youtube.tsx
<div
  className="video-container"
  onClick={evt => {
    evt.preventDefault();
  }}
>
...
</div>
```

추가하려는 rule
```JS
// .eslintrc.js
'jsx-a11y/click-events-have-key-events': 0,
'jsx-a11y/no-static-element-interactions': 0
```

**Comment by jirheee** [comment]
좋은 것 같아요!!

**Comment by hy2850** [comment]
rule 추가 : 715dc30d76ff86b1fc840acf1634170210660c3c
