### ISSUE TITLE
[Backend] API Specification

### ISSUE THREAD

**Issue by jirheee** [CS492-FE-Dev-Team-Project/FE-Dev-Client#38]
## 개요
API를 만들기 전에, 어떤 API가 필요할지 설계를 해야합니다.

## 프로세스
1. 각자 컴포넌트를 만들면서 어떤 API가 필요했는지 작성한다. (아래의 양식 복붙해서 comment에 달기)
2. 그것들을 취합해서 API설계를 한다

#### 개요

어떤 상황에서 쓰는 API인지, 어떤 기능을 가져야 하는지 간략하게 설명

#### Request data
|name|type|required|description|
|---|---|---|-----|
| name of query parameter  |  int, string, ... etc  | requied or optional   | brief description |

#### Return data
|name|type|required|description|
|---|---|---|-----|
| name of query parameter  |  int, string, ... etc  | requied or optional   | brief description |

**Comment by hy2850** [comment]
정인님, API Specification 관련 질문이 있습니다. Request data type이 뭔지 잘 모르겠습니다.  데이터를 요청하는데 필요한 추가적인 정보인가요?
그렇다면, Request data type과 Query parameters가 어떤 차이가 있는지 잘 모르겠습니다. 

<br>

예를 들어 DB의 Marker 테이블로부터 모든 timeline marker 정보를 가져오고 싶다면 (**사실 이 기능만 있으면 됩니다**),
```SQL
SELECT *
FROM Marker
```
(이 경우엔 모든 정보를 가져오는거니까 딱히 request data나 query parameter가 필요 없을 것 같고.)

개중 생성 시간이 10초~30초 사이인 marker 정보만 가져오고 싶다면,
```SQL
SELECT *
FROM Marker
WHERE time BETWEEN 10 and 30
```

Request data type
```JS
{
  timeStart: 10;
  timeEnd: 30
}
```

Query parameters
| name                    | type                 | required            | description       |
| ----------------------- | -------------------- | ------------------- | ----------------- |
| timeStart | int | optional | time range start |
| timeEnd | int| optional | time range end |

이렇게 쓸 수 있는데 말이죠.

**Comment by jirheee** [comment]
아 HTTP라고 생각하고 템플릿을 만든거라 그런건데, Request Data type의 경우 POST할때 같이 보내는 json의 타입을 말한거고, query parameter의 경우 url(ex.`localhost:5000/api/something?queryparameter1=1`)로 전해지는 변수입니다!
- [query param vs path variable](https://ryan-han.com/post/translated/pathvariable_queryparam/)

**Comment by hy2850** [comment]
### 1. getAllTimelineMarkerInfo
#### 개요
(`client/src/components/youtube.tsx` YouTube player component 내부에서) Timeline marker 정보를 DB에 요청해서 받아오기. 
받아온 정보 (아직 미정 - marker가 위치할 시간, 메시지 정보 등)를 바탕으로 player 위에 마커 생성

#### Request data type
전체 마커 정보를 다 불러오거나, 특정 타입의 마커 정보만 불러오도록

| name                    | type                 | required            | description       |
| ----------------------- | -------------------- | ------------------- | ----------------- |
| markerType | MarkerType | required | request markers with certain type or everything |

#### Return data type

Timeline marker의 핵심적인 정보 (추후 변경 가능)

| name                    | type                 | required            | description       |
| ----------------------- | -------------------- | ------------------- | ----------------- |
| time | number | required |  time (in seconds) when marker was set |
| message | string | optional |  message in the marker |

한 마커의 type은 위처럼 설정하고, API는 여러 마커들의 정보를 Array<Info> 형태처럼 반환

**Comment by jirheee** [comment]
조금 많아서, 위의 형태 그대로 하려니까 넘 길어지네요! 일단 간략하게 목록을 만들었습니다.
### Lobby API (Lobby Page에서 사용될 API들)
- [ ] Create Class
새 Class를 만들 때 사용하는 API
- Request

|name | type | required | description|
|-- | -- | -- | --|
|name | string | required | Name of the New Class|
|title | string | optional | Subtitle - Optional|

- Return

|name | type | description|
|-- | -- | -- | 
|classCode | number | Class code for Join|
|title | string | Name of the New Class|
|subtitle | string | Subtitle of new class|

- [ ] Join Class
기존의 Class에 Join할 때 사용하는 API

- Request

|name | type | required | description|
|-- | -- | -- | --|
|classCode | number | required | Class code|

- Return

|name | type | description|
|-- | -- | -- | 
|classCode | number | Class code|
|name | string | Name of the Joined Class|
|subtitle | string | Subtitle of Joined Class|

- [ ] Get Class List
Lobby Page에서 보일 유저가 속한 Class 목록 가져오는 API

- Request

Nothing

- Return
Array of Below Data type.
|name | type | description|
|-- | -- | -- | 
|classCode | number | Class code|
|name | string | Name of the Joined Class|
|subtitle | string | Subtitle of Joined Class|

### In Class API (Class Page에서 사용될 API)
#### Out Lecture
- [ ] Get Lecture List
- [ ] Get Student List
- [ ] Get Chatting
Classmate과의 채팅 가져오는 API
- [ ] Create Lecture
새 Lecture을 만드는 API (Instructor만 가능)

#### In Lecture
- [ ] Create TimeMarker
- [ ] Get TimeMarker Chatting
- [ ] Send Audiomessage

**Comment by hy2850** [comment]
## In Lecture - Timeline Marker 

- [ ] Create TimeMarker

일단 원하는 시간대에 마커 만들고, 마커 클릭하면 slack thread 처럼 작동하도록

#### Request data type

| name       | type       | required | description                           |
| ---------- | ---------- | -------- | ------------------------------------- |
| time       | number     | required | time (in seconds) when marker was set |
| markerType | MarkerType | required | type of the marker - for coloring     |

#### Return data type

| name     | type   | required | description                                                |
| -------- | ------ | -------- | ---------------------------------------------------------- |
| markerID | number | required | 생성된 마커의 id를 client 쪽에서 API 재호출 없이 알기 위해 |

<br>

---

- [ ]   Get TimeMarker Chatting

마커 클릭하면, 관련된 메시지(채팅)이 떠야함 - slack thread 처럼 

#### Request data type

| name     | type   | required | description                    |
| -------- | ------ | -------- | ------------------------------ |
| markerID | number | required | 해당 마커의 채팅 기록 가져오기 |



#### Return data type

표시할 Message

| name     | type    | required | description                       |
| -------- | ------- | -------- | --------------------------------- |
| userName | string  | required |                                   |
| isMy     | boolean | required | to distinguish if message is mine |
| date     | Date    | required | message creation date             |
| message  | string  | required |                                   |

🔥 isMy를 어떻게 판단할까? `client/src/data/chatMessages.ts`에 있는 더미데이터엔 있길래 일단 가져왔는데..
➡️ 각 사용자가 자신의 userID가 뭔지 알고 있게 하고, Message에 작성자 `userID`를 저장해서 비교하는 방법?

<br>

---

- [ ]  Create TimeMarker Chatting

#### Request data type

메시지가 생성돼서 보관될 마커ID + 메시지 정보들

| name     | type    | required | description                                   |
| -------- | ------- | -------- | --------------------------------------------- |
| markerID | number  | required | in which marker do you wish to store messages |
| userName | string  | required |                                               |
| isMy     | boolean | required | to distinguish if message is mine             |
| date     | Date    | required | message creation date                         |
| message  | string  | required |                                               |


#### Return data type

None

**Comment by jirheee** [comment]
Wiki에 작성하기로 해서 Close
