### ISSUE TITLE
[Frontend+Backend] Discussion room (messages) for each Timeline Marker

### ISSUE THREAD

**Issue by hy2850** [CS492-FE-Dev-Team-Project/FE-Dev-Client#45]
#39 아래 이슈 해결
`🚨Timeline Marker 일단 만들고, 나중에 작업할 수 있게`

####  해결책 1) 
원하는 시간대에 버튼 눌러서 마커를 일단 만들기. 
나중에 마커를 클릭 했을 때, 오른쪽 채팅창이 Discussion 창으로 바뀌면서 slack thread처럼 활용될 수 있도록.
Discussion 내부의 메시지는 실시간 채팅과는 다르게 모두 **DB에 저장되어서**, 나중에 Lecture로 다시 돌아와서 볼 수 있음.

- [x] 1. #35 맨 아래 Todo - `Timeline component 클릭 시, 이벤트 등록`
  - [x] 1-1. (API) Marker와 관련된 메시지 가져오기 (Get)
  - [x] 1-2. 메시지 정보 채팅창에 표시
- [x] 2. (API) 메시지 생성 (Create)
- [x] 3. Marker discussion 종료하고, 원래 실시간 채팅으로 돌아가기 (exit)

**Comment by hy2850** [comment]
1번 기능 구현을 위해, timeMarker 컴포넌트 클릭 시 Socket을 통해 chat 컴포넌트에 '어떤 마커가 클릭됐는지' 정보를 전달합니다.

Step1) `client/src/components/timeMarker.tsx`에서 Socket을 통해 `TimeMarkerClicked` 이벤트를 보내고,
```JS
socket?.emit('TimeMarkerClicked', payload);
```
→ Step2) `server/src/ioHandler/index.ts`에서 이벤트 처리해서 **sender에게만** 동일한 `TimeMarkerClicked` 이벤트 보내고
```JS
const OnTimeMarkerClicked = (socket: Socket) => (request: string) => {
  const { lectureId, markerId } = JSON.parse(request);

  socket.emit('TimeMarkerClicked', `${markerId}`);
};

socket.on('TimeMarkerClicked', OnTimeMarkerClicked(socket));
```

→ Step3) `client/src/components/chat.tsx`에서 이벤트 받으면, DB API를 통해 해당 마커와 관련된 메시지들 받아서 표시합니다.
```TS
useEffect(() => {
  socket?.on('TimeMarkerClicked', () => {
    // 🐛 get real 'messages' data related with timeMarker by calling DB API
    setMessages(dummyMessages);
  });
}, [connected]);
```

**Comment by hy2850** [comment]
3번 기능을 구현하려는데, 
Marker thread (Slack thread랑 유사)를 종료하고 다시 돌아가는 기능은 Chat 컴포넌트 `<Header>`의 `<CloseButton>` 클릭하는 것으로 구현하면 될 것 같습니다.

![image](https://user-images.githubusercontent.com/39735858/143161234-a860bc62-591e-4819-b6e9-157950fdbdce.png)

채팅 컴포넌트를 '일반 모드 (실시간 채팅) / thread 모드 (marker 클릭 시)'로 나눠서, 각 모드마다 적절한 채팅을 보여주도록 구현하려고 합니다.

```TS
`client/src/components/chat.tsx`

// 0 : live chatting, 1 : thread mode (timeMarker), 2 : ...
const [chatMode, setChatMode] = useState(0); 
```

### 문제점
유저가 thread를 종료하면 실시간 채팅으로 돌아가야 하는데, 
- 원래는 그냥 빈 채팅창으로 돌아가도록
- 그러나, 유저가 discussion을 보는 도중 다른 사람들이 친 실시간 채팅을 모아서 보여주는게 더 자연스럽다

라고 생각했습니다.

일단 marker thread 채팅은 DB에서 받아오는 것으로 정했고,
실시간 채팅은 어떤 식으로 구현되는지 잘 모르지만, `chatMode`에 따라 다른 채팅을 보여주는 식으로 구현하겠습니다.

**Comment by jirheee** [comment]
제 생각에는 두가지 방법이 있을 것 같습니다.

1. 채팅 컴포넌트를 겹쳐두어서 따로 관리한다
2. 서버쪽에서 채팅 데이터를 메모리에 저장해두고 전체 채팅일때 쏴준다

둘다 가능한 방안일 것 같습니다.

**Comment by hy2850** [comment]
채팅 컴포넌트 하나만 가지고 모드 바꿔가면서 실시간채팅/TimeMarker discussion 보여주는 것보다는 1번 방법이 낫겠네요.
```js
<Chat mode='Live'>
<Chat mode='Discussion'>
<Chat mode='Private'>
```

2번은 서버에서 Socket을 통해 받은 실시간 채팅을 저장해뒀다가, 요청 들어오면 쏴준다는 이야기로 이해했습니다. 맞는지 모르겠네요. 그런데 1로 구현하다면 굳이 저장할 필요 없을 것 같네요.  
`<Chat mode='Live'>`에다가 실시간으로 채팅 모아뒀다가, mode 바뀌면 저 컴포넌트를 보여주면 되니까요.

**Comment by hy2850** [comment]
@jirheee 정인님, `client/src/components/chat.tsx` 구현하신거 보니까, 
props로  header 정보를 받는 것으로 봐선, 
외부에서 필요한 데이터를 넣어주면 표시만 하는 controlled component로 만들고 싶으셨던 건가요?
```JS
const Chat = ({ header, hasHeader }: ChatProps) => { ... }
```

지금 Chat 내부에서 메시지를 fetch하는 식으로 구현할지, 아니면 controlled component 개념을 밀고 나가서 외부에서 모든 데이터를 넣어주는 식으로 구현할지 갈피를 못 잡고 있습니다.

**Comment by hy2850** [comment]
In-lecture API 구현으로 완성
