### ISSUE TITLE
[Frontend] Lobby page Add class modal

### ISSUE THREAD

**Issue by jhlee98** [CS492-FE-Dev-Team-Project/FE-Dev-Client#46]
- 로비 페이지에서 수업을 추가하는 컴포넌트 생성
- 로비 페이지에서 수업에 참가하는 컴포넌트 생성

**Comment by jhlee98** [comment]
add class modal 관련해서 몇가지 질문이 있습니다.

1. 
![image](https://user-images.githubusercontent.com/68766445/142998178-6e7b06ec-3f0b-4bd4-b8bc-a90869afe753.png)

여기서 modalState === ClassAddModalState.JOIN 일 때 
joinContent를 실행시킬려면 이런식으로 &&를 이용하면 되는건가요?

2. 
![image](https://user-images.githubusercontent.com/68766445/142998441-a09961d2-282b-4ba5-8bb7-1180a279aab0.png)

여기서 chakra-ui 의 Input을 사용하여 만들었습니다.
 입력한 값이 밑의 세이브를 눌렀을 때 class data 에 append가 되게 하고싶은데 잘 안되어서 어떤식으로 해야할지 궁금합니다

**Comment by jhlee98** [comment]
또한 수업 참가할때는 특정 코드를 이용해서 참가하는것으로 생각하였는데, 지금 만들어져있는 dummyClasses 에는 코드로 할만한게 title(과목코드) 인데 이것만 입력해서 참가하도록 할까요?

**Comment by hy2850** [comment]
1. 잘 하신 것 같습니다!
2. Save 컴포넌트에 click listener를 추가하면 될 것 같은데요, 예를 들면

```JS
ddd
```

**Comment by jhlee98** [comment]
네 그러면 join 관련해서는 classid 를 받는 형식까지만 만들어놓도록 하겠습니다.

**Comment by jhlee98** [comment]
![image](https://user-images.githubusercontent.com/68766445/143017976-963409a4-d840-4df4-9982-087952602598.png)


![image](https://user-images.githubusercontent.com/68766445/143018003-46f7d325-7c23-4cdd-b3d4-63d82f1adce1.png)

제가 한 스크립트 안에서 save를 누르기 전까지 일어나는 모든 일들을 
위의 tempdata에 저장했다가 나중에 save를 누를 때 한번에 업데이트를 하고 싶은데 
밑의 사진처럼 onChangename(tempdata)를 하여 tempdata를 인수로 받고 
함수 선언할때 썼던 e로 tempdata.title = e.target.value 이런식으로 구현을 하고 싶습니다. 혹시 onChangename 의 인자 부분을 어떻게 선언해야 하나요?

**Comment by hy2850** [comment]
보통 input의 내용은 React state에 저장하고, onChange에는 setState 함수를 넣어서 state를 바꿔주는 식으로 구현합니다.

**Comment by jhlee98** [comment]
그렇군요. 고맙습니다^^
오늘중으로 이슈 마무리 하고 다음 이슈로 넘어가겠습니다

**Comment by jhlee98** [comment]
해결했습니다. 2번의 문제였네요
