### ISSUE TITLE
[Deploy] Frontend + Backend build & server environment 만들기

### ISSUE THREAD

**Issue by jirheee** [CS492-FE-Dev-Team-Project/FE-Dev-Client#47]
- [x] Server에서 Webpage router 만들어서 웹페이지 호스팅
- [x] Frontend build -> Backend serving 자동화

**Comment by jirheee** [comment]
`Unexpected token error`이 계속 떠서 삽질하다가, 일단 react app을 express 서버에서 serve하는건 미루고, 프록시를 설정해서 api server과 별개로 개발하기로 했습니다 ㅜㅜ

**Comment by jirheee** [comment]
해결했습니다! 브라우저 캐시를 모두 지우고 실행하니 되네요 :)

**Comment by jirheee** [comment]
일단 머지했는데 혹시 `yarn build:run` 실행 시 오류가 생기면 이 이슈에 커멘트 달아주세요!

**Comment by hy2850** [comment]
굉장히 사소한건데,

### 문제점
`root/package.json`
```JSON
"build:server": "yarn build:client && cp -r ./client/build/* ./server/client && cd server && yarn build",
```

에서 `cp -r ./client/build/* ./server/client` 부분에서 Not a directory 에러가 나더라구요.

### 원인 및 해결
`./server/client` 폴더가 없어서 그랬습니다.
`mkdir ./server/client`로 해결 가능하고, "build:server" 스크립트에 추가해도 될 듯 하네요.

**Comment by jirheee** [comment]
앗 네네 수정해서 메인에 올려주실 수 있으신가요?

**Comment by hy2850** [comment]
```JSON
"build:server": "yarn build:client && mkdir ./server/client && cp -r ./client/build/* ./server/client && cd server && yarn build",
```
처럼 수정하려고 했으나, 윈도우가 `mkdir ./server/client` 경로를 인식을 못하네요 ([참고](https://chcamp17.com/ko/17-mkdir-create-directory-from-command-line.html#:~:text=subfolder2/subfolder21/folder4-,%EB%AA%85%EB%A0%B9%20%EA%B5%AC%EB%AC%B8%EC%9D%B4%20%EC%98%AC%EB%B0%94%EB%A5%B4%EC%A7%80%20%EC%95%8A%EC%8A%B5%EB%8B%88%EB%8B%A4.,-%EC%9D%B4%20%EC%98%A4%EB%A5%98%EA%B0%80%20%EB%B0%9C%EC%83%9D%ED%95%98%EB%A9%B4))


또 다른 에러를 뱉어내기에, 그냥 직접 터미널에 `mkdir ./server/client` 치는게 좋을 것 같습니다.
