### ISSUE TITLE
[질문] YouTube Component Height 관련 질문 있습니다.

### ISSUE THREAD

**Issue by Jung-Sanghyun** [CS492-FE-Dev-Team-Project/FE-Dev-Client#50]
- #27 

제가 ClassroomPage 제작하면서 현철님이 제작하신 YouTube Component를 넣었는데, Component의 width는 100%로 지정하면 화면에 딱 맞게 설정되는데, height는 제대로 설정되지 않습니다. 제가 해결해보려 한 방법은 다음과 같습니다.

1. Height를 100%로 지정했을때 - 
![image](https://user-images.githubusercontent.com/84287503/143010897-462e32c6-ab6d-4111-8f54-44f43846fa2a.png)
위와 같이 높이가 매우 작게 지정됨.
2. Chakra의 AspectRatio 같은 component 사용 - iframe이 아니라 적용이 안됨
3. Component의 width를 숫자로 구하여 16:9 비율로 height를 숫자로 지정 - component의 width를 숫자로 구하는 방법을 찾아봐도 잘 모르겠습니다.

해결방법을 같이 생각해보면 좋을 것 같습니다.

**Comment by hy2850** [comment]
제가 제작한 YouTube Component는 props로 width, height를 받는데, 지금은 픽셀(px)값을 받도록 해뒀습니다. 

```JS
const YouTubePlayer = ({
  name,
  studentNumber,
  room,
  videoId,
  width = 640,
  height = 360
}: userInfo)=>{...}

// 사용 예시
  <YouTube
    name={user.name}
    studentNumber={user.studentNumber}
    room={user.room}
    videoId="j1_5ttGRzFs"
    width={600}
    height={400}
  />
```

> 1. Height를 100%로 지정했을때 
를 어떻게 하셨는지 잘 모르겠는데, 혹시 구현하신 코드를 코멘트에 바로 올려주실 수 있으신가요?

**Comment by hy2850** [comment]
3번 방법을 통해, width/height 픽셀값을 직접 뽑아낼 수 있으면 제 코드는 그대로 사용 가능할 것 같고,
1번 방법을 사용하려면, `YouTubePlayer`의 props로 들어가는 width, height를 optional props로 바꾼 뒤, `client/style/youtube.css`의 맨 첫번째를
```CSS
#youtube-wrapper {
  position: relative;
  width: 100%;
  height: 100%;
}
```
로 바꿔보면 되지 않을까 싶습니다.

**Comment by Jung-Sanghyun** [comment]
픽셀 값을 받도록 되어있었는데 화면에 딱 맞추기 위해서
```JS
<YouTube
  name={user.name}
  studentNumber={user.studentNumber}
  room={user.room}
  videoId="j1_5ttGRzFs"
  width="100%"
  height="100%"
/>
'''
로 해보고있었는데 말씀해주신 방법으로 해보겠습니다. 감사합니다.

**Comment by hy2850** [comment]
제가 리팩토링을 아직 안해서 코드가 보기 매우 힘든데, 막히시는 부분 있으시면 언제든지 불러주세요! 바로 돕겠습니다.

**Comment by Jung-Sanghyun** [comment]
```JS
#youtube-wrapper iframe {
  width: 100%;
  height: 100vh;
}
```
css에 위의 코드를 추가하여 해결하였습니다.
