### ISSUE TITLE
[Frontend] Left Menu Component 수정

### ISSUE THREAD

**Issue by jirheee** [CS492-FE-Dev-Team-Project/FE-Dev-Client#55]
현재 Left Menu Component의 경우 가장 아래에 존재하는 exit, setting button이 디자인과 다른 것 같습니다!(icon button이어야 하는데 현재는 text와 함께 있음)
차후에 번연 관련해서 locale 버튼이 들어가게 될 것을 고려하면 수정이 필요할 것 같네요 :)
![image](https://user-images.githubusercontent.com/65358599/143020349-c474b840-11de-4a43-85bc-eb57d67b6998.png)

**Comment by Jung-Sanghyun** [comment]
classroom Page 만들면서 같이 수정하겠습니다.
