### ISSUE TITLE
[Frontend]Create lecture

### ISSUE THREAD

**Issue by jhlee98** [CS492-FE-Dev-Team-Project/FE-Dev-Client#66]
### 수업 생성시 필요한 Input 값

수업의 구조는 실시간 수업과 비실시간 수업이 있으므로 처음에 수업을 생성할 때 이러한 요소 두개를 다 설정하는게 좋다고 봅니다.

실시간 수업
- 수업에 사용될 Youtube 링크
- 수업하는 시각 ( 날짜, 시각)
- 수업 제목

비실시간 수업(수업 외에 기본적으로 떠있는 화면)
- 수업 pdf 첨부
- 공지사항

다른 채팅 기능, 마커 기능 등은 항상 활성화 되어있는 상태로 하면 될 것 같습니다.
코멘트를 주시면 추가하겠습니다.

디자인은 들어가야 하는 요소가 다 정해지면 디자인하도록 하겠습니다.

**Comment by jirheee** [comment]
저희 기획에서 실시간 수업과 비실시간 수업이 따로 나뉘어져 있지 않아서, 구별을 할 필요는 없을 것 같습니다

**Comment by jirheee** [comment]
저희 기획에서 수업이라 함은, 유튜브를 선생님과 제자들이 라이브로 보는것을 의미하므로,
- 수업에 사용될 Youtube 링크
- 수업하는 시각 ( 날짜, 시각)
- 수업 제목
말씀하신 것처럼 위 내용들이 들어가야 할 것 같고,
만약 퀴즈를 넣는다면 수업을 만들 때 강의의 어떤 시점에서 팝 퀴즈를 넣고, 그 내용물을 정하는 것도 여기서 해야할 것 같습니다.

**Comment by jhlee98** [comment]
네 알겠습니다

**Comment by jhlee98** [comment]
![image](https://user-images.githubusercontent.com/68766445/143522769-f8c53a8f-5670-44a4-8bee-821a434e30e7.png)

강의 생성 page는 다음과 같이 디자인하였습니다.

**Comment by jirheee** [comment]
퀴즈 생성할 때 재생 목록의 어떤 영상, 몇 초에 마커가 나올지 정해야 할 것 같습니다!

**Comment by jhlee98** [comment]
네 퀴즈 생성 모달안에 그것을 넣을려고 합니다. Youtube URL은 여러개를 입력할 수 있게 해놓을까요?

**Comment by jirheee** [comment]
- https://github.com/CS492-FE-Dev-Team-Project/FE-Dev-Client/pull/31
위 이슈 참고하시면 재생목록 링크를 입력하도록 하면 될 것 같습니다.

**Comment by jirheee** [comment]
그리고 퀴즈 생성 모달안에 두더라고, 바깥쪽에서 몇번째 영상인지, 몇초인지 볼 수 있도록 하는 것이 좋을 것 같습니다

**Comment by jirheee** [comment]
그리고 플레이리스트를 입력했을 때 재생 목록에 존재하는 영상들을 받아와서 표시하도록 기획했던 것 같은데 youtube api보시면서 구현하시면 될 것 같습니다

**Comment by hy2850** [comment]
재호님, 다음 API 공식 문서 참고하셔서, 필요한 함수 찾아서 쓰시면 됩니다.
https://developers.google.com/youtube/iframe_api_reference?hl=ko



아래 두 함수 쓰셔서 재생목록 ID로 로드하시고, 재생목록에 있는 영상 정보들 받아와서 처리하심 됩니다

1. [재생목록 로드](https://developers.google.com/youtube/iframe_api_reference?hl=ko#:~:text=%EC%95%84%EB%9E%98%EC%97%90%20%EC%84%A4%EB%AA%85%EB%90%98%EC%96%B4%20%EC%9E%88%EC%8A%B5%EB%8B%88%EB%8B%A4.-,cuePlaylist,-Argument%20syntax)
`player.cuePlaylist`

2. [재생목록 정보 가져오기](https://developers.google.com/youtube/iframe_api_reference?hl=ko#Retrieving_playlist_information)
`player.getPlaylist():Array`

<br>

위 문서에 나온 예제 코드는 HTML에 script를 삽입하는 식이라, React tsx 코드에선 못쓸겁니다.
대신 YouTube API를 포장해놓은 youtube-player 패키지 이용해주세요
https://www.npmjs.com/package/youtube-player#examples

**Comment by jhlee98** [comment]
yarn add youtube-player로 설치하였는데 
![image](https://user-images.githubusercontent.com/68766445/143858077-90912954-a1bc-4dc2-a235-5490757e3f3e.png)
다음과 같은 에러가 뜨네요...

**Comment by hy2850** [comment]
`yarn add @types/youtube-player` 해보시겠어요? 타입이 정의가 안되어있어서 뜨는 에러같은데

**Comment by jhlee98** [comment]
네 그부분은 해결하였습니다. 고맙습니다.
처음에 Player을 선언하여야 player.cueplaylist를 가져오는데
Player를 어떻게 선언하여야 하나요?

**Comment by hy2850** [comment]
`player = YouTubePlayer('video-player');`

위에 올려드린 [npm 링크](https://www.npmjs.com/package/youtube-player#:~:text=player%C2%A0%3D%C2%A0YouTubePlayer(%27video%2Dplayer%27)%3B) 타고 가서 보니까 이렇게 나와있네요.

**Comment by jhlee98** [comment]
네 그렇게 했었는데 element 이슈가 떠서 질문하였었습니다

**Comment by hy2850** [comment]
에러 캡쳐해서 올려주시겠어요?

**Comment by jhlee98** [comment]
![image](https://user-images.githubusercontent.com/68766445/143865601-2a551d00-d63c-4069-abe5-728db99ac3a8.png)
네 저도 구글링 계속 하고 있는데 이번 에러는 잘 안나오네요

**Comment by jhlee98** [comment]
저게 'video-player'해도 같은 에러가 뜹니다

**Comment by hy2850** [comment]
```JS
const player = YouTubePlayer('video-player');
let playlistObj = player.cuePlaylist('list= 뒤의 문자열')
```
이렇게 해도 안된다는 말씀이시죠?

**Comment by jhlee98** [comment]
네. 위에 player 선언에서 에러가 뜹니다

**Comment by hy2850** [comment]
모듈 자체의 문제 같은데... stackoverflow에서 같은 문제를 겪는 사람들을 찾아보거나 소스코드를 뜯어봐야 할 것 같아요

**Comment by jirheee** [comment]
제 생각에 youtube player library를 이용하는게 아니라, googleapi의 playlistitems api를 이용해야 할 것 같습니다.

**Comment by jirheee** [comment]
이 링크 참고하셔서 구현하시면 될 것 같습니다. https://brunch.co.kr/@joypinkgom/76

**Comment by jhlee98** [comment]
https://yarnpkg.com/package/youtube-playlist-info

전에 올려주신 블로그대로 하다가 잘 안되어서
제가 다른 링크도 찾아보았는데 둘 다

const ypi = require('youtube-playlist-info');
require을 사용하는데 error 가 떴습니다.
그래서 이 부분은 eslint 에 예외설정을 하면 된다하여 수정을 해보았는데

![image](https://user-images.githubusercontent.com/68766445/143910217-a7d453bf-dabb-4ed0-b483-e131dccd4475.png)

이러한 에러가 떴고 제가 구글링을 해보았지만 해결을 못하였습니다. low level db issue 관련이 많이 나오던데 혹시 이러한 에러 아시는 분이 계신가요

**Comment by jhlee98** [comment]
유튜브 api는 카카오톡으로 공유하겠습니다

**Comment by hy2850** [comment]
모듈이 outdated 돼서 나타나는 현상인데, youtube-playlist-info 깃헙 레포 가보니까, 마지막 업데이트가 4년전이네요. 저 에러를 고치려면 소스코드를 손봐야할텐데, 아무래도 못 쓸것 같습니다.

**Comment by jhlee98** [comment]
네 정인님이 소개해주신걸로 진행하고있습니다

**Comment by jhlee98** [comment]
여러 모듈로 진행해보았는데
우선 googleapis 를 사용하면 http2 모듈도 함께 사용해야 합니다.
그 후 
import { google } from 'googleapis';
와
![image](https://user-images.githubusercontent.com/68766445/144074156-67466def-f3ba-4f4f-8bde-143353a817bc.png)
이 코드를 실행하게 되면

localhost:5000 에서 화면이 하얗게 뜨고 
![image](https://user-images.githubusercontent.com/68766445/144074270-b5ccf743-8d59-4dd1-a9a9-5700511f10c0.png)

framer 에러가 뜨게 됩니다. 

그래서 찾아낸 방법이 axios를 쓰는 것이었습니다.

axios를 사용하였을 때  youtube 링크를 잘 받아올 수 있었습니다.

**Comment by hy2850** [comment]
지금 LobbyPage 아래에 create lecture 컴포넌트가 그대로 있어서 이걸 classPage로 옮길려고 하는데,
Instructor가 'Create new lecture' 버튼을 누르면..
1. modal 창이 뜨게 한다 
2. 새 페이지로 라우팅

컴포넌트 내부에 이미 모달창이 있어서 2번 방법이 좋을 것 같은데 어떻게 생각하시는지

**Comment by hy2850** [comment]
저희 그리고 퀴즈 기능 넣을건가요? 이거 관련 entity, API 새로 만들고 시간 될 때 퀴즈 띄우는 기능도 새로 만들어야 합니다. 다음주까지는 힘들 것 같아요.

일단 리마인드겸 이슈 남깁니다.

**Comment by jirheee** [comment]
네 저도 새 페이지로 라우팅되는게 좋을 것 같습니다.

**Comment by jirheee** [comment]
퀴즈는 우선순위를 조금 미뤄두어도 될 것 같아요!

**Comment by hy2850** [comment]
퀴즈 제외 create lecture 기능까지만 회의 전까지 마무리하겠습니다
