### ISSUE TITLE
[UI] Timemarket 생성 버튼의 위치

### ISSUE THREAD

**Issue by jirheee** [CS492-FE-Dev-Team-Project/FE-Dev-Client#67]
- #39 

현재는 마커 생성 버튼이 채팅창에 있는데, 여기에 배치했던 이유가 마커와 함께 특정 메세지를 첨부하려고 했고, 그렇기에 채팅 입력과 마커 생성 버튼을 가까이에 두었던 것으로 기억합니다.
그런데 기획이 바뀌어서 마커 생성을 하면, 바로 생성이 되고 마커를 클릭했을 때 해당 쓰레드로 채팅창이 넘어가는 것으로 되었습니다. 
따라서 마커 생성 버튼을 유튜브 쪽으로 배치하는건 어떨까 라는 생각이 드는데, 다른 분들의 의견이 궁금합니다.

**Comment by hy2850** [comment]
중앙에 저런 floating button 만들어서, 클릭하면 timeline marker 생성되도록 하는게 좋을 것 같네요.

![image](https://user-images.githubusercontent.com/39735858/143533328-6dd2dad1-a12c-4d18-a3d8-8fb05422b7a1.png)

**Comment by hy2850** [comment]
저희가 MarkerType을 4종류로 정해뒀는데
```JS
type MarkerType = 'question' | 'quiz' | 'notice' | 'discussion';
```

일단 마커를 생성하면 디폴트로 question이 되고, 이후 채팅 컴포넌트의 헤더에 있는 'Marker Type' 버튼을 통해 마커 타입을 바꿀 수 있게 만들어보겠습니다.
![image](https://user-images.githubusercontent.com/39735858/143563726-635ffc39-9703-48ff-89bd-b553719b553d.png)
