### ISSUE TITLE
[Bug] LeftMenu Classname Bug

### ISSUE THREAD

**Issue by jirheee** [CS492-FE-Dev-Team-Project/FE-Dev-Client#68]
Classname이 아래처럼 두번 뜨네요 🥲
![image](https://user-images.githubusercontent.com/65358599/143374795-7c3e71fe-1c05-44a0-9d27-0e982a2ccd6b.png)

**Comment by Jung-Sanghyun** [comment]
확인했습니다. 디자인 정리하면서 수정하겠습니다
