### ISSUE TITLE
[UI] FontSize 통일

### ISSUE THREAD

**Issue by jirheee** [CS492-FE-Dev-Team-Project/FE-Dev-Client#69]
현재 화면을 보면, 아래와 같이 폰트 크기가 굉장히 작고 통일성이 없어서, 폰트 크기를 전체적으로 키우고 사이즈를 통일해야 할 것 같습니다
![image](https://user-images.githubusercontent.com/65358599/143375029-d14bd853-08c5-43fb-bc00-5e1b0bc29bf7.png)

**Comment by Jung-Sanghyun** [comment]
- #64
