### ISSUE TITLE
[질문] Socket 연결/이벤트 처리가 안되는 것 같습니다

### ISSUE THREAD

**Issue by hy2850** [CS492-FE-Dev-Team-Project/FE-Dev-Client#78]
Socket 이벤트를 처리하는 서버 파일의 Logger 혹은 console.log가 아예 안찍히네요.

https://github.com/CS492-FE-Dev-Team-Project/FE-Dev-Client/blob/3075879b26bccbf8a36016409ef07aaee1a55b83/server/src/ioHandler/index.ts#L44

TimeMarker 클릭해서 Socket event 호출하는 기능도 현재 작동하지 않는데, 정상적인 현상인지 궁금합니다.
(이러면 아마 Instructor - participant sync도 작동 안할 것 같네요)

**Comment by jirheee** [comment]
메인에 있는 코드로 리베이스해서 시도해보시겠어요?

**Comment by jirheee** [comment]
ClassPage에 소켓 context가 제공되어 있는지 확인 부탁드립니다

**Comment by jirheee** [comment]
어떤 상황에서 소켓 사용하시는지도 달아주시면 도움 드릴 수 있을 것 같습니다

**Comment by hy2850** [comment]
rebase 후 소켓 context 제공된 것 확인한 뒤에 잘 되는 것 확인했습니다. 이슈 close할게요.
