### ISSUE TITLE
[질문] 실행 관련

### ISSUE THREAD

**Issue by jhlee98** [CS492-FE-Dev-Team-Project/FE-Dev-Client#79]
![image](https://user-images.githubusercontent.com/68766445/143517471-dd66ca39-779c-40f4-a669-0cfce8bb4941.png)

항상 yarn start로 실행을 하였었는데 하던대로 실행하니 이런식으로 계속 떠서
물어봅니다...

**Comment by jirheee** [comment]
- #54 에 쓰여진것처럼 UserProvider수정하시면 됩니다!

**Comment by jhlee98** [comment]
Can't import the named export 'Children' from non EcmaScript module (only default export is available)
![image](https://user-images.githubusercontent.com/68766445/143519372-7a530482-27e0-4f9d-a637-fcb6626cf67d.png)
혹시 이 에러는 뭔지 아시나요? 
찾아보니 버전의 문제라고는 하는데

**Comment by hy2850** [comment]
뭔가 충돌이 난 것 같은데..
일단 client 작업하시니, client 폴더로 가셔서 `yarn start`로 해서 작업해보시겠어요?

**Comment by jhlee98** [comment]
클라이언트 가서 yarn start 해도 같은이슈 떠서요..

**Comment by jhlee98** [comment]
client 폴더에가서 yarn 실행
server 폴더에가서 yarn 실행
root 에서 yarn 후
yarn build:run 하니까 실행되었습니다.

다만 cp관련 이슈가생겨서 서버쪽은 사용을 못하고 있습니다.
